### ISSUE TITLE
Credentials secret name cannot be changed

### ISSUE THREAD

**Issue by djbobyd** [truecharts/library-charts#268]
### App Name

paperless-ng

### SCALE Version

Not using SCALE

### App Version

4.0.50

### Application Events

```Shell
The application is hanging on init state when installing on a regular k8s cluster with modified credentials secrets names.
```

### Application Logs

```Shell
There are no logs, but the issue is coming from the init container not being able to get the right credentials for the Redis instance.
```

### Application Configuration

snippets of the offending change
```
postgresql:
  enabled: true
  existingSecret: "paperless-dbcreds"
```
```
redis:
  enabled: true
  existingSecret: "paperless-rediscreds"
```

### Describe the bug

According to the available values, I am allowed to change the name of the secret that contains the credentials to both postgres and redis. 
Therefore, I changed it as I don't want the secret files to collide with ones from other applications using the same services. The secrets with the new names have been created successfully, and the name change is reflected in the stateful sets of the corresponding services. The change is also partially reflected in the Deployment manifest of the paperless-ng app. It is only corrected in the containters section. However, the change is not reflected in the initContainers section, thus the init container is failing.
Looking through the code of the library chart it seems the name of the secret is hardcoded in tc.common.controller.prepare. 

### To Reproduce

Install paperless-ng chart, but add the following snippets to the values file during installation:
```
postgresql:
  enabled: true
  existingSecret: "paperless-dbcreds"
redis:
  enabled: true
  existingSecret: "paperless-rediscreds"
```

### Expected Behavior

I would expect that the init container also takes the secret names from the provided configuration.

### Screenshots

none applicable

### Additional Context

I am using a regular k8s cluster installed on bare metal, not installing on truenas.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Valid, but low priority though…

The option should be removed as all apps depend on thus specific secret structure.

**Comment by djbobyd** [comment]
Hi,
I don't think it is a good idea to have several applications sharing one and the same database. This might lead to performance and compatibility issues. I definitely prefer the design one DB per App, even when I am running on TrueNAS SCALE. 
It shouldn't be that difficult to check for the custom name and if not set to use the defaults.

**Comment by Ornias1993** [comment]
I was saying we use the same secret design everywhere which cannot be replaced with arbitrary names.

**Comment by Ornias1993** [comment]
I never talked about sharing databases ever and even commented on fixing the underlaying issue.

locking, aa design discussions are not appreciated on Github.

**Comment by Ornias1993** [comment]
As we've dropped support for deployments outside of TrueNAS SCALE, this issue can be closed. 
As SCALE by-design always deploys things in their own namespaces.
