### ISSUE TITLE
Tailscale addon secret RBAC errors

### ISSUE THREAD

**Issue by markbergsma** [truecharts/library-charts#315]
### App Name

tailscale addon

### SCALE Version

22.12.0

### App Version

home-assistant 2023.1.6_18.0.32

### Application Events

```Shell
2023-01-27 17:03:26
Back-off restarting failed container
2023-01-27 17:03:25
Container image "tailscale/tailscale:v1.34.1@sha256:69bec9fdea25765e1b9dd129ccaeaf1e160f1132bb390535772fa939f0bf620b" already present on machine
2023-01-27 17:03:25
Created container tailscale
2023-01-27 17:03:25
Started container tailscale
```

### Application Logs

```Shell
2023-01-27 15:49:51.827749+00:00boot: 2023/01/27 15:49:51 Some Kubernetes permissions are missing, please check your RBAC configuration: multiple errors:
2023-01-27 15:49:51.827859+00:00missing get permission on secret "tailscale"
2023-01-27 15:49:51.827892+00:00missing update permission on secret "tailscale"
```

### Application Configuration

N/A

### Describe the bug

Using the tailscale addon doesn't work and the container fails with these log errors:

Appears to have been addressed by #292 and related refactoring, but may still need an update of the container image to new version 1.36 for the addon in the common library.

              I think this may still need an update of the tailscale image to newly released v1.36; the common library is still pinned to v1.34.1.

_Originally posted by @markbergsma in https://github.com/truecharts/library-charts/issues/303#issuecomment-1406677255_
            

### To Reproduce

N/A

### Expected Behavior

Tailscale completing start

### Screenshots

N/A

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Don't repost things that are already closed as being finished.
Just because it hasn't made a release doesn't mean it should be reposted.
