### ISSUE TITLE
vpn plugin: support mounting vpn config from secret when running as helm chart

### ISSUE THREAD

**Issue by gclawes** [truecharts/library-charts#323]
### Is your feature request related to a problem?

Related to running applications with VPN plugin (openvpn or wireguard) in helm chart mode. 

The `vpnconfig` volumeMount only supports mounting a file from a hostPath, specifically the `mountPath` (below) is the vpn config file (`/vpn/vpn.conf` for openvpn, `/etc/wireguard/wg0.conf` for wireguard).
https://github.com/truecharts/library-charts/blob/6625467e5536e02f1a0aac97fc0cbe97ab2a7cb6/library/common/templates/addons/vpn/openvpn/_container.tpl#L57
https://github.com/truecharts/library-charts/blob/6625467e5536e02f1a0aac97fc0cbe97ab2a7cb6/library/common/templates/addons/vpn/wireguard/_container.tpl#L52

This prevents a secret being used as the source of the config volume in `.Values.addons.vpn.configFile`.

### Describe the solution you'd like

When mounting the vpn `configFile` as a secret, support a subpath in the `volumeMount` so the secret data key can be mounted in the given volumeMount file path.

### Describe alternatives you've considered

Support fully configurable additional volumeMount options for VPN containers, as described here: https://github.com/truecharts/library-charts/pull/281

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
The Addons where previously HEAVILY cut-down to only suite TrueNAS SCALE.

They will, most likely, be reworked later this year. As the current state is pretty mediocre.

**Comment by gclawes** [comment]
With the re-opening of the helm repo, would re-examining https://github.com/truecharts/library-charts/pull/281 be a reasonable change in the short-term?

**Comment by Ornias1993** [comment]
What I tried to explain is that the addons will, likely, be complete reworked later this year.
Which means i'm not going to do small patches in the mean time.

**Comment by Ornias1993** [comment]
We've added the option to mount a single folder besides the configfile in the refactor.
at the moment adding secret support is not a priority for us still though...

**Comment by Ornias1993** [comment]
existing secret support also added :)
