### ISSUE TITLE
Unable to use cert-manager TLS certificates on any application ingresses

### ISSUE THREAD

**Issue by croemmich** [truecharts/library-charts#364]
### App Name

All (Home Assistant, PhotoPrism, Custom Apps, etc.)

### SCALE Version

22.12.0

### App Version

Latest

### Application Events

```Shell
No relevant events
```

### Application Logs

```Shell
No relevant events
```

### Application Configuration

```
[x] Enable Ingress
  Hosts:
    HostName: hass.example.com
    Paths:
      Path: /
      Path Type: Prefix
  clusterIssuer: cloudflare
  (Advanced) Traefik Entry Point: websecure
```
or
```
[x] Enable Ingress
  Hosts:
    HostName: hass.example.com
    Paths:
      Path: /
      Path Type: Prefix
  TLS-Settings
    Certificate Hosts
      Host: hass.example.com
    Use Cert-Manager clusterIssuer: cloudflare  
  (Advanced) Traefik Entry Point: websecure
```

### Describe the bug

The rendered ingress resource does not include the `cert-manager.io/cluster-issuer: cloudflare` annotation and the `tls` section does not include a `secretName`. 

When using the top level `clusterIssuer` (rather than the one nested in TLS-Settings), the entire `tls` section is absent.

Looking through this repo, it looks like you may be manually creating the certificate resource rather than relying on the annotation, which would work, however the certificate object is not created either.

Manually editing the ingress to include the annotation and proper tls section results in a certificate being issued correctly.

### To Reproduce

1. Deploy cert-manager
2. Deploy any application using the ingress configuration described in Application Configuration above

### Expected Behavior

The ingress is configured to use the specified clusterissuer and certificate.

### Screenshots

-

### Additional Context

-

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
Cert-Manager requires new-common which is not released for stable or enterprise train yet.

please check the website and discord next time.

**Comment by Ornias1993** [comment]
Also: this repo should not be used to report anything, except proven bugs with common.

for bugs with apps, even multiple, please dont assume its common related and file on the main repo please.
