### ISSUE TITLE
[BUG] Apps configured with service type "Simple" keep exposing port on host after switching type.

### ISSUE THREAD

**Issue by miguelangel-nubla** [truecharts/library-charts#41]
### App Name

All

### SCALE Version

22.02.0

### App Version

All

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
N/A
```

### Application Configuration

N/A

### Describe the bug

App reachable on host port when it should not be.

### To Reproduce

With truecharts and traefik already set up:
1. Create app from TrueCharts catalog with service type "Simple" and without ingress.
2. Check app exposed correctly on port on the main TrueNAS IP.
3. Edit the app and change service type to ClusterIP, and enable ingress with the hostname.
4. App available both on http://[truenas-ip]:[port] and http://hostname.

It does not happen if app created directly with service type "ClusterIP" and ingress.

### Expected Behavior

App only available on ClusterIP and ingress.

### Screenshots

N/A

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
This is a known upstream bug within the loadbalancer used buy TrueNAS SCALE.
There is nothing we can de about this. Please next time try to verify these kinds of issues on the Discord first :)

**Comment by Ornias1993** [comment]
Also: issues here are ignored. Please only file issues in the primary repo

**Comment by miguelangel-nubla** [comment]
Ok will do,
link to the upstream bug for reference?

**Comment by Ornias1993** [comment]
No idea, don't really care as it's not my problem.
might be fixed on nightly though...
