### ISSUE TITLE
[gluetun] out of date

### ISSUE THREAD

**Issue by paller** [truecharts/library-charts#493]
### App Name

gluetun vpn addon

### SCALE Version

22.12.0

### Train Name

stable

### App Version

v3.34.3

### Latest Available Container Version

v3.35

### Link to container

https://github.com/qdm12/gluetun/pkgs/container/gluetun/versions?filters%5Bversion_type%5D=tagged

### Additional Context

Gluetun recently added support for wireguard port forwarding with protonvpn.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
I doubt this is so much outdated that it warrants an issue.

**Comment by paller** [comment]
It depends. As a user of Proton VPN this is a very big update, for anyone else it's irrelevant.

Since the other solutions got deprecated and replaced by Gluetun as the official VPN sidecar for all, I would have assumed there would be some sort of automatic tracking of upstream releases instead of a case by case evaluation. If new features in Gluetun doesn't warrant an update, what does?

**Comment by Ornias1993** [comment]
I think you're not aware of our policies about when you're allowed to file issues for outdated containers.
