### ISSUE TITLE
Add automatic Homepage labels (option)

### ISSUE THREAD

**Issue by Ornias1993** [truecharts/library-charts#573]

**Comment by stavros-k** [comment]
Note: make it expandable, there are multiple apps that work similar (eg Flame)

**Comment by Ornias1993** [comment]
I think I rather pick one of them for official TrueCharts support.
We also don't support multiple ingresses for this reason.

**Comment by stavros-k** [comment]
all those are annotatetiom based.
So it's should be easily doable

**Comment by Ornias1993** [comment]
It's doable for sure.
But I don't want to bloat it with supporting multiple options.

Users can already add annotations, it's just a short cut to pick one project we like to officially support and the others can just set annotations.
