### ISSUE TITLE
clusterissuer not hard requiring kubernetes-reflector on cluster certificate setup

### ISSUE THREAD

**Issue by Migsi** [truecharts/library-charts#614]
### App Name

clusterissuer

### Operating System

TrueNAS SCALE 23.10.0'or 23.10.0.1

### App Version

4.2.10

### Application Events

```Shell
cleared, due to reboot
```

### Application Logs

```Shell
cleared, due to reboot
```

### Application Configuration

![grafik](https://github.com/truecharts/library-charts/assets/11976939/141aceab-d42f-4869-969c-95f3b2aca5b6)
![grafik](https://github.com/truecharts/library-charts/assets/11976939/b8a942ed-8626-4457-a22d-d49ac90959b4)

I didn't screenshot usernames/passwords and hosts to redact them. They are there and valid, I can guarantee that.

### Describe the bug

The certificate gets created properly, so there is no real error on the clusterissuer side of things, but no application is able to use the cluster certificate, as kubernetes-reflector was not installed yet.

### To Reproduce

Setup traefik, cert-manager, clusterissuer, etc. following the manuals, but skip the point of "install kubernetes-reflector" when setting up the cluster certificate. Try to access any app which is set up to use this cluster certificate and get presented the default (selfsigned) traefik cert.

### Expected Behavior

The setup of a cluster certificate within clusterissuer should fail/not allow me to save due to kubernetes-reflector being missing.

### Screenshots

Unfortunately none.

### Additional Context

None.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
@Migsi I'm going to close this due to multiple reason:

1. Its not a bug, its a missing feature
2. We don't do lookups anymore (or prefer to not use them for fail-cases), so we also don't do dependency lookups anymore. SO this feature cannot be implemented anyway.
