### ISSUE TITLE
HomePage integration Enhancement, disable widgets

### ISSUE THREAD

**Issue by shadofall** [truecharts/library-charts#653]
### Is your feature request related to a problem?

Since not all Applications have widget components. but integration can be turned on for them. this can result in the Tile showing missing widget type.

![image](https://github.com/truecharts/charts/assets/9327622/a1a7b65a-c862-41a3-8a93-499137e75d17)

### Describe the solution you'd like

An option to turn of the widget.* aspects for integration per application

### Describe alternatives you've considered

alternative is to document that if you wish to add applications with out widgets you will need to do so manually via the service.yaml file

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
not going to be fixed anytime soon.

**Comment by shadofall** [comment]
I'll be sure to document it then.
