### ISSUE TITLE
homepage intergration bug, install of 2 applications and name left blank

### ISSUE THREAD

**Issue by shadofall** [truecharts/library-charts#654]
### App Name

homepage

### Operating System

TrueNAS SCALE 23.10.1

### App Version

15.0.12

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
N/A
```

### Application Configuration

![image](https://github.com/truecharts/charts/assets/9327622/2a46b447-cf6f-4000-a185-ccdc50bcc448)
![image](https://github.com/truecharts/charts/assets/9327622/82243568-abce-427e-a68f-6d84fde7b8f5)

### Describe the bug

Widget componet gets confused when the same app is set twice and diffrent name is not specified in one, this is probably likely more a homepage bug and will file a report with them as well but if we can mitigate it great. if not i can document it as well. Deplyoment name doesnt have to match they just need different Name Values

### To Reproduce

isntall 2 versions of same app. with integration name field blank for both and setup widget components with diffrent api keys

Change the name on one. and it starts working fine

### Expected Behavior

diffrent installs of same app should show proper api desite same name

### Screenshots

With Name not Set for second install

![image](https://github.com/truecharts/charts/assets/9327622/dcfe594f-0f05-462f-b814-ed82d49e9c5c)

with name set to match deployed name

![image](https://github.com/truecharts/charts/assets/9327622/a71b32cc-b005-4a3b-9d4e-92c84183ddbe)

Sonarr/Sonarr2 name but still same installs showing only the names need to be diffrent not match the deployment

![image](https://github.com/truecharts/charts/assets/9327622/6ad774d9-1026-491f-8423-582edbf8e565)

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
No this is our mistake.
