### ISSUE TITLE
Application with Ingress and TrueNAS SCALE Certificate can no longer be installed/upgraded

### ISSUE THREAD

**Issue by scrool** [truecharts/library-charts#665]
### App Name

metube

### Operating System

TrueNAS SCALE 23.10.1

### App Version

2023-12-13_10.0.0

### Application Events

```Shell
(none - failed validation of the data for new app)
```

### Application Logs

```Shell
(none - failed validation of the data for new app)
```

### Application Configuration

![01](https://github.com/truecharts/library-charts/assets/27489/ef338d86-8658-4979-b176-44e8d8f45547)
![02](https://github.com/truecharts/library-charts/assets/27489/aa74d450-2a80-4939-9677-1dc066b44d9e)
![03](https://github.com/truecharts/library-charts/assets/27489/3028745b-905c-4bc2-a538-1d018cf370e2)
![04](https://github.com/truecharts/library-charts/assets/27489/36a3ca7d-ee70-4541-b411-b380508d2a6c)
![05](https://github.com/truecharts/library-charts/assets/27489/6b386b91-ed4c-4466-a620-818722f9bb50)
![06](https://github.com/truecharts/library-charts/assets/27489/b19a929a-59f0-4286-a693-cb640abfad79)
![07](https://github.com/truecharts/library-charts/assets/27489/08342e73-8ce1-4414-9801-c38e817f362c)
![08](https://github.com/truecharts/library-charts/assets/27489/6d67ca06-bef4-4530-ac80-ba12446e47ed)
![09](https://github.com/truecharts/library-charts/assets/27489/ab381570-8286-4555-b7c7-09b0c25af4fd)
![10](https://github.com/truecharts/library-charts/assets/27489/e33c961e-1862-4240-b9ec-6886396b4f96)

Changes are highlighted with red frame. The certificate name was anonymized - instead of the real domain and its reference I have used example.com.

### Describe the bug

New application instance - here Metube - that would use (deprecated) TrueNAS Scale certificate fails validation with an error: "[EFAULT] Failed to install App: Ingress - Expected non-empty [hosts] ".

### To Reproduce

In TrueNAS Scale web UI ensure to have TrueCharts repo enabled then:

1. click on Apps on the left hand side pane
2. click on button Discover Apps
3. search for metube
4. click on Install button
5. scroll all the way down to  Networking and Services -> Configure Service(s) -> Main Service -> Service Type and change it to Cluster IP (Do Not Expose Ports)
6. scroll to Ingress -> Main Ingress and check the checkbox Ingress.
7. next to Hosts click on Add
8. in the newly available HostName field enter some hostname
9. in the very same section (Ingress) check the checkbox next to Show Advanced Settings
10. next to the newly appeared "TLS-Settings" hit button Add
11. in the newly appeared dropdown "Use TrueNAS SCALE Certificate (Deprecated)" select one of the Scale Certificate
12. scroll all the way down and hit Install button

### Expected Behavior

The application is installed.

### Screenshots

Following popup appears:
![popup-error](https://github.com/truecharts/library-charts/assets/27489/19aae2b6-2d87-4233-8446-e4762e98de1c)

and when I click on More Info I get a traceback:

![popup-traceback-03](https://github.com/truecharts/library-charts/assets/27489/457b6abe-9485-4ed6-9cf8-56ba8b066185)
![popup-traceback-02](https://github.com/truecharts/library-charts/assets/27489/9d1eadf4-7ad8-46e5-a59b-50ce64df7876)
![popup-traceback-01](https://github.com/truecharts/library-charts/assets/27489/bc75f5d1-1ed0-487d-9c46-36226292260e)

### Additional Context

I believe this was caused by #621.

Older version of the Metube: App Version: 2023.12.13, Chart Version: 8.1.5 was installed with the same configuration just fine. This older version cannot be updated to: 2023-12-13_10.0.0 - I get the same error as for the new application installation.

I understand that use of TrueNAS Scale certificate is deprecated in favor of Certificate Manager. I would appreciate to be able to use this (unsupported) configuration for some time if possible.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
The error is quite clear, it states " Expected non-empty [hosts]" and your certificate hosts list is empty.
Please next time try to file a support ticket first.
