### ISSUE TITLE
Automatic chown/chmod broken

### ISSUE THREAD

**Issue by billybednar** [truecharts/library-charts#668]
### App Name

plex

### Operating System

TrueNAS SCALE 22.12.4.1 or prior

### App Version

1.32.8.7639

### Application Events

```Shell
-
```

### Application Logs

```Shell
(job template modified to prevent deletion on hook completion)
# k3s kubectl logs plex-autopermissions-d67mt -n ix-plex
Starting auto permissions job...
Automatically correcting ownership and permissions...
Automatically correcting permissions for /mounts/persist-list-0...
chmod: 666: No such file or directory
chmod: invalid mode '-$'
Failed setting permissions using chmod...
Permissions after: [2777]
Permissions after: [2777]

Automatically correcting ownership for /mounts/persist-list-0...
/bin/sh: /usr/sbin/nfs4xdr_winacl: not found
Failed setting ownership using winacl...
Ownership before: [0:568]
Ownership after: [0:568]

Finished auto permissions job...
```

### Application Configuration

![image](https://github.com/truecharts/library-charts/assets/1000201/72b36889-3f54-48bd-8178-77f44611f4e6)

### Describe the bug

Automatic permissions configuration fails to `chown` or `chmod` the storage when the recursive option is selected as the `-R` argument is typoed as `-$`. Under SCALE, `chown` also fails when recursive is not selected as `nfs4xdr_winacl` is not available inside the container. The first "Permissions after" line in the output should be say "before".

### To Reproduce

1. Set type of config or additional storage to Host Path or emptyDir
2. Under Automatic Permissions Configuration, check enabled, Run CHOWN, and Recursive.
3. Set Run CHMOD to 666
4. Install/update
5. Check permissions of storage with ls

### Expected Behavior

Permissions are changed

### Screenshots

-

### Additional Context

https://github.com/truecharts/library-charts/blob/7329b73a7bf05f792ffe5aa77ab299e40c8358a0/library/common/templates/lib/util/_autoperms.tpl#L104-L127

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by Ornias1993** [comment]
> @Ornias1993 typos are fixed, can you check the binary (nfs4xdr_winacl)?

https://github.com/truecharts/containers/blob/master/base/alpine/Dockerfile

**Comment by billybednar** [comment]
Oops, I saw "not found" and assumed it assumed it was missing. Not sure exactly why it doesn't run.
```
/ $ /usr/sbin/nfs4xdr_winacl
/bin/ash: /usr/sbin/nfs4xdr_winacl: not found
/ $ stat /usr/sbin/nfs4xdr_winacl
  File: /usr/sbin/nfs4xdr_winacl
  Size: 43784           Blocks: 58         IO Block: 44032  regular file
Device: 1000a6h/1048742d        Inode: 98991       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-29 12:20:35.000000000 +0000
Modify: 2023-09-29 12:20:35.000000000 +0000
Change: 2023-12-28 12:10:57.502017497 +0000
/ $
```

**Comment by Ornias1993** [comment]
Hmm might be only "x" on other?
