### ISSUE TITLE
nil pointer evaluating interface {}.ixChartContext

### ISSUE THREAD

**Issue by Thiryn** [truecharts/library-charts#691]
### App Name

hedgedoc

### Operating System

Other Using Helm (please specify)

### App Version

11.1.9

### Application Events

```Shell
n/a
```

### Application Logs

```Shell
n/a
```

### Application Configuration

n/a

### Describe the bug

helm template with an incompatible helm version fails with templating error. nil pointer evaluating interface {}.ixChartContext

### To Reproduce

Hedgedoc requires helm 3.12. Running helm 3.11, and templating hedgedoc at its latest version (the values provided are just here to allow passing the templating dependencies)
```
docker run alpine/helm:3.11.1 template oci://tccr.io/truecharts/hedgedoc --version 11.1.9 --set cnpg.main.enabled=false,workload.main.podSpec.containers.main.env.CMD_DB_HOST=none,workload.main.podSpec.containers.main.env.CMD_DB_PASSWORD=none
```

### Expected Behavior

helm templating working

### Screenshots

n/a

### Additional Context

Traced the issue down to here https://github.com/truecharts/library-charts/blob/main/library/common/templates/lib/chart/_check_capabitilies.tpl#L14

The `.Values.global.ixChartContext` should probably either be `$rootCtx.Values.global.ixChartContext` or `$.Values.global.ixChartContext` based on usages in other places in the repo.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.

**Comment by bbodenmiller** [comment]
Seeing the same on drawio 8.1.12+ chart

**Comment by stavros-k** [comment]
> Seeing the same on drawio 8.1.12+ chart

An issue with the library affects potentially every chart.  +1 is never needed on an open issue.
