### ISSUE TITLE
Ability to update Gluetun server list

### ISSUE THREAD

**Issue by JordanDiefenbach** [truecharts/library-charts#703]
### Is your feature request related to a problem?

Yes, the server list for my provider AirVPN is outdated and since Gluetun runs with nonpersistent storage I cannot use the update environment variable to update the server.json list.

### Describe the solution you'd like

The ability to update the server.json list

### Describe alternatives you've considered

I've considered not using Gluetun and just using Wireguard with my Truecharts apps

### Additional context

This is the page for the Gluetun server list update feature. https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
@stavros-k I think we should:
A. add emptyDir storage
B. Enable fetching for those lists always
