### ISSUE TITLE
Share Additional App Storage mounts with tailscale addon

### ISSUE THREAD

**Issue by bionoren** [truecharts/library-charts#730]
### Is your feature request related to a problem?

This is effectively a workaround for #635 - if I can mount storage into the tailscale container, I can pass `--statedir=/mountpoint` to tailscaled and persist state.

### Describe the solution you'd like

I would like an app's "additional app storage" mounts, specifically (not any app-specific mounts that might cause weird conflicts, just the additional ones (i.e. `persist-list-#` in the helm chart)), to be mounted in the tailscale container (part of the container's volumeMounts).

### Describe alternatives you've considered

#635 (and its duplicate) have explored this some already. Ideally we would resolve that, or expose a way to set the `tailscalestate` volume to a PVC, but I would be perfectly happy with this solution. I was surprised when I looked at the chart yaml and saw that additional app storage was *not* shared with the tailscale container.

### Additional context

I also run the tailscale app, but I want to have the tailscale addon for a particular app so I can have a persistent DNS name to share with family (and not have them worrying about port numbers, or me worrying about correctly defining ACLs).

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by bionoren** [comment]
If this is something you are open to, I would be happy to put together a PR for it

**Comment by Ornias1993** [comment]
https://github.com/truecharts/library-charts/issues/635 is the correct solution, no one disputes that.
We're not going to rewrite the complete common library persistence section to add this feature instead.

Denied.
