### ISSUE TITLE
Add the redis depencies to custom-app

### ISSUE THREAD

**Issue by yodatak** [truecharts/library-charts#748]
### Is your feature request related to a problem?

Hi i want to try to use with helm custom-app the affine install and maybe made a PR when its ready but the custom-app don't have the redis depencies so it not automaticly install redis with common-lib

How can i do to add redis to custom-app helm chart ?

### Describe the solution you'd like

the redis depencies added 

### Describe alternatives you've considered

add manualy redis

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by yodatak** [comment]
maybe somethink like this could make it works
https://github.com/truecharts/helm-staging/blob/de0390963a8527502786dc14ada006b8d7d8636b/charts/stable/n8n/Chart.yaml#L19

**Comment by Ornias1993** [comment]
Also @yodatak Why the heck did you add this issue to the common chart?
This literally has nothing to do with the common chart.
