### ISSUE TITLE
Support the disable of  server side encryption for cnpg cluster

### ISSUE THREAD

**Issue by yodatak** [truecharts/library-charts#849]
### Is your feature request related to a problem?

I want to backup cnpg cluster to minio s3 but the default config try to do server side encryption in my bucket and i don't have in minio, by default it try encryption

### Describe the solution you'd like

Permit to do variables or disable wal encryption 
https://github.com/truecharts/library-charts/blob/main/library/common/templates/lib/cnpg/cluster/_backup.tpl

```
  barmanObjectStore:
    wal:
      encryption: AES256
    data:
      encryption: AES256
```

the minio documentation about KES/KVM 
https://min.io/docs/minio/linux/operations/server-side-encryption.html#minio-sse-data-encryption

with cnpg documentation
https://cloudnative-pg.io/documentation/1.23/wal_archiving/#wal-archiving

### Describe alternatives you've considered

I manualy remove `encryption: AES256` in my cluster

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
Interesting feedback, it's a shame that CNPG folks never clarify that this setting is related to the KES/KVM mess that is minio.

**Comment by yodatak** [comment]
They saye but its not realy clear "You can configure the encryption directly in your bucket, and the operator will use it unless you override it in the cluster configuration."
